// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHg2Lr-CgxCuGYgDCBhcklST-NigjEVF4',
    appId: '1:517045073961:web:08a40afe8921ae88488438',
    messagingSenderId: '517045073961',
    projectId: 'hospitese2',
    authDomain: 'hospitese2.firebaseapp.com',
    databaseURL: 'https://hospitese2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hospitese2.appspot.com',
    measurementId: 'G-CB8B4Q70LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB5hE2OFogKEcbHzxQsHqK1_MdL6F9amw',
    appId: '1:517045073961:android:75730eae60d4d8f7488438',
    messagingSenderId: '517045073961',
    projectId: 'hospitese2',
    databaseURL: 'https://hospitese2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hospitese2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHg2Lr-CgxCuGYgDCBhcklST-NigjEVF4',
    appId: '1:517045073961:web:fdc2de53d2aad122488438',
    messagingSenderId: '517045073961',
    projectId: 'hospitese2',
    authDomain: 'hospitese2.firebaseapp.com',
    databaseURL: 'https://hospitese2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hospitese2.appspot.com',
    measurementId: 'G-K4CV43W72F',
  );
}
